#!/usr/bin/env bash

${1:="--full"}

if [[ "$1" != "--full" ]] || [[ "$1" != "--basic" ]]; then
    echo "[ERROR] '$1' is invalid"
    echo "[+] You can use './install.sh --basic' for a basic install"
    echo "[+] Just use './install.sh' for a full install on supported OS's"
    exit 1
fi

if [[ ! -f $HOME/.config/mbromell/env.sh ]]; then
    source ./scripts/init-env.sh $1
    mkdir -p $HOME/.config/mbromell
    env_file=$HOME/.config/mbromell/env.sh

    # Setting config vars
    echo "# WARNING: DO NOT EDIT THIS FILE" > $env_file
    echo "# Auto-generated from $DOTFILES/install.sh" >> $env_file
    echo "export DOTFILES=\"$DOTFILES\"" >> $env_file
    echo "export DOTFILES_OS=\"$DOTFILES_OS\"" >> $env_file
    echo "export DOTFILES_STOW=\"$DOTFILES_STOW\"" >> $env_file
else
    source $HOME/.config/mbromell/env.sh
fi

pushd $DOTFILES/home
for dir in $DOTFILES_STOW; do
    echo "[+] Stowing :: $dir"
    # Ignore pointless bug warnings
    # https://github.com/aspiers/stow/issues/65#issuecomment-1465060710
    stow -t $HOME -D $dir \
        2> >(grep -v 'BUG in find_stowed_path? Absolute/relative mismatch' 1>&2)
    stow -t $HOME $dir
done
popd
