#!/usr/bin/env bash

if [[ ! -f ${HOME}/.config/dotfiles/env.sh ]]; then
    ./scripts/init-env.sh
    mkdir -p ${HOME}/.config/dotfiles
    env_file=${HOME}/.config/dotfiles/env.sh
    stow_files="$(ls -d */)"

    if [[ "${DOTFILES_OS}" != "unknown" ]]; then
        stow_files="$(cat ${DOTFILES}/stow/${DOTFILES_OS}.txt | tr "\n" " ")"
    fi

    # Setting config vars
    echo "# WARNING: DO NOT EDIT THIS FILE" > ${env_file}
    echo "# Auto-generated from ${DOTFILES}/install.sh" >> ${env_file}
    echo "export DOTFILES=\"${DOTFILES}\"" >> ${env_file}
    echo "export DOTFILES_OS=\"${DOTFILES_OS}\"" >> ${env_file}
    echo "export DOTFILES_STOW=\"${stow_files}\"" >> ${env_file}
    source ${env_file}
fi

pushd ${DOTFILES}/home
for dir in ${DOTFILES_STOW}; do
    echo "[+] Stowing :: $dir"
    # Ignore pointless bug warnings
    # https://github.com/aspiers/stow/issues/65#issuecomment-1465060710
    stow -t $HOME -D $dir \
        2> >(grep -v 'BUG in find_stowed_path? Absolute/relative mismatch' 1>&2)
    stow -t $HOME $dir
done
popd
