#!/usr/bin/env bash

case "$(uname -a)" in
    Linux*microsoft-standard-WSL2*) dotfiles_env="wsl" ;;
    Linux*)                         dotfiles_env="linux" ;;
    Darwin*)                        dotfiles_env="mac" ;;
    *)                              dotfiles_env="unknown" ;;
esac

if [[ "$dotfiles_env" == "unknown" ]]; then
    echo "[ERROR] Unkown OS environment of: $(uname)"
    echo "[+] Exiting install as to not cause any damage."
    exit 1
fi

# Setting config vars
echo "# WARNING: DO NOT EDIT THIS FILE" > $HOME/.dotrc
echo "# Auto-generated from $(pwd)/install.sh" >> $HOME/.dotrc
echo "export DOTFILES=\"$(pwd)\"" >> $HOME/.dotrc
echo "export DOTFILES_ENV=\"${dotfiles_env}\"" >> $HOME/.dotrc
source $HOME/.dotrc

if ! command -v nix-env &> /dev/null; then
    echo "[+] Installing nix package manager for nix-env"
    if [[ "$DOTFILES_ENV" == "mac" ]]; then
        sh <(curl -L https://nixos.org/nix/install) --yes
    elif [[ "$DOTFILES_ENV" == "wsl" ]]; then
        sh <(curl -L https://nixos.org/nix/install) --yes --no-daemon
    else
        sh <(curl -L https://nixos.org/nix/install) --yes --daemon
    fi
    # Restart shell after install.
    $SHELL -l
fi

if ! command -v zsh &> /dev/null; then
    echo "[+] Installing zsh"
    nix-env -iA nixpkgs.zsh
fi

if [[ "$SHELL" != "/bin/zsh" ]]; then
    echo "[+] Setting ZSH as default shell"
    chsh -s $(which zsh)
fi

if [[ -z "${ZSH}" ]]; then
    echo "[+] Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "[+] Installing powerlevel10k theme for zsh"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

# Install brew casks for mac
if [[ "$DOTFILES_ENV" == "mac" ]]; then
    if ! command -v brew &> /dev/null; then
        echo "[+] Installing Homebrew"
        NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "[+] Installing brew cask 'alt-tab', 'iterm2'"
        brew install --cask alt-tab iterm2 linearmouse usr-sse2-rdm
    fi
fi

source $DOTFILES/dotfiles/.config/dotfiles/functions.sh
dotnix
dotstow

$SHELL -l
