#!/usr/bin/env bash

if [[ ! -f $HOME/.config/mbromell/env.sh ]]; then
    mkdir -p $HOME/.config/mbromell
    env_file=$HOME/.config/mbromell/env.sh

    # Setting config vars
    echo "# WARNING: DO NOT EDIT THIS FILE" > $env_file
    echo "# Auto-generated from $DOTFILES/install.sh" >> $env_file
    echo "export DOTFILES=\"$DOTFILES\"" >> $env_file
else
    source $HOME/.config/mbromell/env.sh
fi

source $DOTFILES/scripts/os.sh

stow_files="$(cat $DOTFILES/stow/linux.txt)"
[[ "$OS" == "mac" ]] && stow_files="$(cat $DOTFILES/stow/mac.txt)"

pushd $DOTFILES/home
for dir in $stow_files; do
    echo "[+] Stowing :: $dir"
    # Ignore pointless bug warnings
    # https://github.com/aspiers/stow/issues/65#issuecomment-1465060710
    stow -t $HOME -D $dir \
        2> >(grep -v 'BUG in find_stowed_path? Absolute/relative mismatch' 1>&2)
    stow -t $HOME $dir
done
popd
