---@diagnostic disable: missing-fields
require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "css",
    "gdscript",
    "godot_resource",
    "javascript",
    "kdl",
    "lua",
    "markdown_inline",
    "python",
    "rust",
    "svelte",
    "typescript",
    "yaml",
  },
  auto_install = true,
  autotag = { enable = true },
  endwise = { enable = true },
  indent = { enable = false },
  highlight = {
    enable = true,
    -- For better performance and making sure there is no conflicts
    -- with highlight grups that interact directly with treesitter.
    additional_vim_regex_highlighting = false,
  },
  textobjects = {
    -- [""] = "@assignment.inner",
    -- [""] = "@assignment.lhs",
    -- [""] = "@assignment.outer",
    -- [""] = "@assignment.rhs",
    -- [""] = "@attribute.inner",
    -- [""] = "@attribute.outer",
    ["ib"] = "@block.inner",
    ["ab"] = "@block.outer",
    -- [""] = "@call.inner",
    -- [""] = "@call.outer",
    ["ic"] = "@class.inner",
    ["ac"] = "@class.outer",
    ["ii"] = "@conditional.inner",
    ["ai"] = "@conditional.outer",
    ["if"] = "@function.inner",
    ["af"] = "@function.outer",
    ["il"] = "@loop.inner",
    ["al"] = "@loop.outer",
    -- [""] = "@number.inner",
    ["ip"] = "@parameter.inner",
    ["ap"] = "@parameter.outer",
    -- [""] = "@return.inner",
    -- [""] = "@return.outer",
    -- [""] = "@scopename.inner",
    -- [""] = "@statement.outer",
  },
})
