import = [
    "~/.config/alacritty/nightfox.toml",
]

[font]
size = 16

[font.normal]
family = "Brosevka Nerd Font"
style = "Regular"

[font.italic]
# Explicitly set weight otherwise it will default to thinnest available.
family = "Brosevka Nerd Font"
style = "Italic"

[keyboard]
bindings = [
    { key = "0", mods = "Control", action = "ResetFontSize" },
]
